### ISSUE TITLE
Retribution becomes unresponsive when trying to "Take Off"

### ISSUE THREAD

**Issue by Marto32** [dcs-retribution/dcs-retribution#199]
### Affected versions

v1.2.1

### Description

After the latest DCS update, and after creating / flying a single mission in Retribution, the Retribution app becomes unresponsive when trying to "Take Off"

Steps to reproduce:

 - Open the Retribution app;
 - Plan sortie (must be after one Retribution mission was successfully flown);
 - App becomes unresponsive

I have tried the following to troubleshoot:

 - Restart Retribution and DCS
 - Restart the PC
 - Delete and recreate the `Saved Games/DCS/Retribution` directory

The last item in the list above works and allows me to fly 1 mission, but then the same problem persists when I try to fly another mission after that first one.

If it's helpful, Liberation works completely fine, so this seems to be a Retribution-specific issue.

### Save game and other files

[Caucus - Medium Campaign.zip](https://github.com/dcs-retribution/dcs-retribution/files/12379231/Caucus.-.Medium.Campaign.zip)
[retribution.log](https://github.com/dcs-retribution/dcs-retribution/files/12379250/retribution.log)
[state.zip](https://github.com/dcs-retribution/dcs-retribution/files/12379255/state.zip)

**Comment by Marto32** [comment]
Follow up question, tangential to this issue: is there an active discord server? The invite links I saw on the wiki / README page are invalid.

**Comment by Raffson** [comment]
Just to verify, is this on the beta builds? It the actual release?

**Comment by Raffson** [comment]
> Follow up question, tangential to this issue: is there an active discord server? The invite links I saw on the wiki / README page are invalid.

Which README are you referring to? Because the one on the main page should be valid 😬

https://discord.gg/b4x34Bg4We

**Comment by Marto32** [comment]
Yes, this is on the DCS Open Beta.

And yep, the invite link works, looks like I had to solve a 2FA prompt in discord before it would let me use the link. Thanks!

**Comment by Raffson** [comment]
> Yes, this is on the DCS Open Beta.

I was actually referring to Retribution 😅

**Comment by Marto32** [comment]
Oh, I downloaded the "latest" release from the github release page.

**Comment by Raffson** [comment]
> Oh, I downloaded the "latest" release from the github release page.

In that case, try our latest test/beta build and let me know if the problem persists:
https://github.com/dcs-retribution/dcs-retribution/actions/runs/5730514391

**Comment by Marto32** [comment]
Unfortunately that didn't fix it (at least with my existing saves).

**Comment by Raffson** [comment]
> Unfortunately that didn't fix it (at least with my existing saves).

I'll try to find some spare time today to try reproducing the issue, will keep you posted ;)

**Comment by Raffson** [comment]
A preliminary investigations indicates it's related to the fast-forward to first contact option, somehow it's getting stuck in an infinite loop so I'll dig in for a closer look...

**Comment by Raffson** [comment]
Issue should've been fixed, it was caused by a mismatch between the FF-interrupt type and your flight's start-type. You can download the latest dev-build through the following link (bottom of the page as soon as the build is ready) :

https://github.com/dcs-retribution/dcs-retribution/actions/runs/5911640773

**Comment by Marto32** [comment]
@Raffson this actually doesn't seem to be fixed in that dev version. I'm assuming it's the same issue, and if I change FF interrupt type to "start up" but then I create my own flight where I start "in flight" it seems to enter an infinite loop again (program doesn't respond). Perhaps `self.flight.client_count > 0` isn't working as expected and an "in flight" state needs to be added [here](https://github.com/dcs-retribution/dcs-retribution/blob/66d741d0b3fd25ec3acaac579987b6464c91fed2/game/ato/flightstate/takeoff.py#L49)?

**Comment by Raffson** [comment]
> @Raffson this actually doesn't seem to be fixed in that dev version. I'm assuming it's the same issue, and if I change FF interrupt type to "start up" but then I create my own flight where I start "in flight" it seems to enter an infinite loop again (program doesn't respond). Perhaps `self.flight.client_count > 0` isn't working as expected and an "in flight" state needs to be added [here](https://github.com/dcs-retribution/dcs-retribution/blob/66d741d0b3fd25ec3acaac579987b6464c91fed2/game/ato/flightstate/takeoff.py#L49)?

I don't think we should add another state to that list because the FF interrupt option can't be equal to "InFlight" since the options are limited to "None", "StartUp", "Taxi" & "Takeoff". However I just noticed I wrote a typo where `is` should be replaced with `in` for starters.
Next I think we should implement an override other flight-states like "InCombat", since that should in theory always halt the sim.
I'll give it another shot over the weekend 😉

**Comment by Marto32** [comment]
Oh interesting. I use this in conjunction with auto-resolve combat which is why I figured flight was possible.

I can give the update a shot. Is there a test suite so I know I'm not messing anything else up? I only saw info on linters and type checks in the dev guide.

**Comment by Raffson** [comment]
If you've set up a virtual environment you should be able to run `pytest`, although I'm not sure if the code in question is actually covered by the tests.

But if you're using "auto-resolve" combat and want to start in-flight, I'm doubting as to which condition should be met to halt the sim. For starters I think we should do some debugging and check whether the loop resets the mission time or not, since the initial infinite loop would keep simulating the first few minutes and start over. Perhaps this case is different in the sense that the sim-time keeps progressing indefinitely.
