### ISSUE TITLE
Crash via: 'PySide2.QtWidgets.QWidgetItem' object has no attribute 'width'

### ISSUE THREAD

**Issue by Marto32** [dcs-retribution/dcs-retribution#203]
### Affected versions

Development build

### Test/Development build

https://github.com/dcs-retribution/dcs-retribution/actions/runs/5911640773

### Description

After completing a mission and selecting "Accept Results" and "Okay", Retribution crashes with the following error:

```
'PySide2.QtWidgets.QWidgetItem' object has no attribute 'width'

Traceback (most recent call last):
  File "qt_ui\delegates.py", line 62, in paint
AttributeError: 'PySide2.QtWidgets.QWidgetItem' object has no attribute 'width'
```

The results of the previous mission are not saved and I have to restart the mission again.

### Save game and other files

[Syria Full Map.zip](https://github.com/dcs-retribution/dcs-retribution/files/12525687/Syria.Full.Map.zip)

**Comment by Raffson** [comment]
From my experience this error is not reproducible 😅
Every now and then it pops up, although this is the first time I hear that it's happening on debriefing with a "loss of turn" as a result.
The only thing I can currently think of that would potentially solve this issue is upgrading to PySide6, but no guarantees there 😬

**Comment by Raffson** [comment]
Update to PySide6 has been done, will close the issue meanwhile.
Feel free to reopen it if you run into the issue again 😉
