### ISSUE TITLE
Kiowa doesn't seem to be flyable. 

### ISSUE THREAD

**Issue by fiveo84** [dcs-retribution/dcs-retribution#348]
### Affected versions

v1.3.1

### Description

Downloaded Retribution Zip and the file paths dont match what is on github. Kiowa isn't flyable for any faction. 

### Save game and other files

n/A

**Comment by Raffson** [comment]
Please use our latest dev-build instead: https://github.com/dcs-retribution/dcs-retribution/actions/runs/9653171074

**Comment by Raffson** [comment]
Also recommend joining our discord to have easier access to the dev-builds, because we're not planning on releasing a new version just yet. Also note that your saves should be compatible with later versions of Retribution, although occasionally we miss something which breaks save-compatibility, in which case I'd like to ask you to report it :)
