### ISSUE TITLE
Units being destroyed at mission start

### ISSUE THREAD

**Issue by jsharpcsa** [dcs-retribution/dcs-retribution#57]
### Affected versions

Development build

### Test/Development build

https://github.com/dcs-retribution/dcs-retribution/actions/runs/3814230005

### Description

At mission start, instantly there are 17 losses. The report shows it was these MiGs. Screenshot is attached and miz is as well. This problem can be repeated. 

![image](https://user-images.githubusercontent.com/86506228/210162645-d7f8ffea-173d-4266-b1e2-a2844561ad65.png)

### Save game and other files

https://1drv.ms/u/s!At0XXw_2HmkboIRrWCWIsyRQ5RbBMw?e=7qNncg

This is a OneDrive link to the mission.

**Comment by Raffson** [comment]
Link's broken, but I got your mission through discord. Don't really need a campaign file in this case since it's a known issue in the GH campaign due to the parking spot problem.

Either way, I think I have something that'll at least fix the mid air collisions, and depending on my test's result I may also have a fix to push the AI immediately to their task. This will introduce its own problems on its turn, but I think we'd rather want the flights that spawn in flight to actually go do something instead of entering the pattern to land...

**Comment by Raffson** [comment]
![image](https://user-images.githubusercontent.com/10977187/210173477-bfe942b8-6518-4a38-b80a-28875ad43d2e.png)

Lovely 😂
