### ISSUE TITLE
Support for STRIKE & Escort missions for Apache

### ISSUE THREAD

**Issue by Grizzly35** [dcs-retribution/dcs-retribution#88]
### Is your feature request related to a problem? Please describe.

At the moment Apaches do not fly strike missions by default, you have to set it in the air wing config first. Atm you cannot add mission types when you forgot it in the air wing config.
When planning Air Assault f.e., the Apache cannot used as a escort or pre strike asset in the package to clean up the target area

### Describe the solution you'd like

Setz the apache up for strike missions by default

**Comment by Raffson** [comment]
Liberation has made a pretty big structural change which we incorporated as well, and with that there are some possibilities that present itself. I've just checked the pydcs data and it can definitely be used as a strike platform. Escorting also seems a possibility but that might require some more work because we definitely don't want an Apache to escort a Hornet 😂

**Comment by Raffson** [comment]
@Grizzly35 is STRIKE really necessary? Helicopters can do BAI to clean up certain areas for an AirAssault flight, so I don't see any added value in having helicopters fire at a specific point, because that's essentially how STRIKE works...

Any thoughts? 😅

**Comment by Raffson** [comment]
Considering this one done since it's now possible to properly plan a helicopter package with escorts. Also a lot of work was done in optimizing the flight-plans so that helicopters don't tend to stick to the ground or overspeed...
